apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
# data:
#   SECRET_KEY_BASE:
#   POLKAMARKETS_API_DATABASE_PASSWORD: