default: &default
  <% ENV["ETHEREUM_NETWORK_IDS"].split(',') do |network_id| %>
    network_<%= network_id %>:
      bepro_api_url: <%= ENV["ETHEREUM_NETWORK_#{network_id}_BEPRO_API_URL"] %>
      prediction_market_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_PREDICTION_MARKET_CONTRACT_ADDRESS"].to_s %>"
      realitio_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_REALITIO_ERC20_CONTRACT_ADDRESS"].to_s %>"
  <% end %>
    market_list_url: <%= ENV['ETHEREUM_MARKET_LIST_URL'] %>
    network_ids: <%= ENV["ETHEREUM_NETWORK_IDS"].split(',') %>

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default
