default: &default
  ipfs_api_url: <%= ENV['INFURA_IPFS_API_URL'] %>
  ipfs_project_id: <%= ENV['INFURA_IPFS_PROJECT_ID'] %>
  ipfs_project_secret: <%= ENV['INFURA_IPFS_PROJECT_SECRET'] %>
  ipfs_project_gateway: <%= ENV['INFURA_IPFS_PROJECT_GATEWAY'] %>

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default
